blueprint:
  name: Surveiller des pourcentages et activer un switch (seuils individuels)
  description: >
    Surveille une liste d’input_number (en %) et incrémente des compteurs selon les seuils (20, 30, 50, 75).
    Active ou désactive un input_boolean cible en fonction des compteurs et des seuils d'activation individuels.
  domain: automation
  input:
    surveilles:
      name: Entités surveillées
      description: Liste d’input_number représentant des pourcentages
      selector:
        entity:
          multiple: true
          domain: input_number
    switch_cible:
      name: Switch cible
      description: Input_boolean à activer/désactiver
      selector:
        entity:
          domain: switch
    compteur_20:
      name: Compteur 20%
      selector:
        entity:
          domain: input_number
    seuil_activation_20:
      name: Seuil d’activation 20%
      description: Nombre minimum d’entités >20% pour activer le switch
      default: 1
      selector:
        number:
          min: 1
          max: 75
          step: 1
    compteur_30:
      name: Compteur 30%
      selector:
        entity:
          domain: input_number
    seuil_activation_30:
      name: Seuil d’activation 30%
      default: 1
      selector:
        number:
          min: 1
          max: 75
          step: 1
    compteur_50:
      name: Compteur 50%
      selector:
        entity:
          domain: input_number
    seuil_activation_50:
      name: Seuil d’activation 50%
      default: 1
      selector:
        number:
          min: 1
          max: 75
          step: 1
    compteur_75:
      name: Compteur 75%
      selector:
        entity:
          domain: input_number
    seuil_activation_75:
      name: Seuil d’activation 75%
      default: 1
      selector:
        number:
          min: 1
          max: 75
          step: 1

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  surveilles: !input surveilles
  switch_cible: !input switch_cible

  compteur_20: !input compteur_20
  seuil_20: !input seuil_activation_20
  compteur_30: !input compteur_30
  seuil_30: !input seuil_activation_30
  compteur_50: !input compteur_50
  seuil_50: !input seuil_activation_50
  compteur_75: !input compteur_75
  seuil_75: !input seuil_activation_75

action:
  - variables:
      count_20: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>',20) | list | count }}
      count_30: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>',30) | list | count }}
      count_50: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>',50) | list | count }}
      count_75: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>=',75) | list | count }}

  # Mise à jour des compteurs
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_20 }}"}
    data: {value: "{{ count_20 if count_20 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_30 }}"}
    data: {value: "{{ count_30 if count_30 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_50 }}"}
    data: {value: "{{ count_50 if count_50 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_75 }}"}
    data: {value: "{{ count_75 if count_75 > 0 else 0 }}"}
    
  # Activation / désactivation du switch avec seuils individuels
  - choose:
      - conditions: >
          {{ count_20 >= seuil_20
             or count_30 >= seuil_30
             or count_50 >= seuil_50
             or count_75 >= seuil_75 }}
        sequence:
          - service: switch.turn_on
            target:
              entity_id: "{{ switch_cible }}"
    default:
      - service: switch.turn_off
        target:
          entity_id: "{{ switch_cible }}"
