blueprint:
  name: Surveiller des pourcentages et activer un switch
  description: >
    Surveille une liste d’input_number (en %) et incrémente des compteurs selon les seuils (25, 33, 66, 100).
    Active ou désactive un input_boolean cible en fonction des compteurs.
  domain: automation
  input:
    surveilles:
      name: Entités surveillées
      description: Liste d’input_number représentant des pourcentages
      selector:
        entity:
          multiple: true
          domain: input_number
    switch_cible:
      name: Switch cible
      description: Input_boolean à activer/désactiver
      selector:
        entity:
          domain: input_boolean
    compteur_25:
      name: Compteur 25%
      description: input_number utilisé comme compteur pour le seuil 25%
      selector:
        entity:
          domain: input_number
    compteur_33:
      name: Compteur 33%
      description: input_number utilisé comme compteur pour le seuil 33%
      selector:
        entity:
          domain: input_number
    compteur_66:
      name: Compteur 66%
      description: input_number utilisé comme compteur pour le seuil 66%
      selector:
        entity:
          domain: input_number
    compteur_100:
      name: Compteur 100%
      description: input_number utilisé comme compteur pour le seuil 100%
      selector:
        entity:
          domain: input_number
    valeur_seuil_activation:
      name: Valeur seuil d’activation
      description: Nombre minimum d’entités au-dessus d’un seuil pour activer le switch
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  surveilles: !input surveilles
  switch_cible: !input switch_cible
  compteur_25: !input compteur_25
  compteur_33: !input compteur_33
  compteur_66: !input compteur_66
  compteur_100: !input compteur_100
  seuil_activation: !input valeur_seuil_activation

action:
  - variables:
      count_25: >
        {{ expand(surveilles)
           | selectattr('state','not in',['unknown','unavailable'])
           | map(attribute='state') | map('float')
           | select('>',25) | list | count }}
      count_33: >
        {{ expand(surveilles)
           | selectattr('state','not in',['unknown','unavailable'])
           | map(attribute='state') | map('float')
           | select('>',33) | list | count }}
      count_66: >
        {{ expand(surveilles)
           | selectattr('state','not in',['unknown','unavailable'])
           | map(attribute='state') | map('float')
           | select('>',66) | list | count }}
      count_100: >
        {{ expand(surveilles)
           | selectattr('state','not in',['unknown','unavailable'])
           | map(attribute='state') | map('float')
           | select('>=',100) | list | count }}

  # Mise à jour des compteurs
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_25 }}"}
    data: {value: "{{ count_25 if count_25 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_33 }}"}
    data: {value: "{{ count_33 if count_33 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_66 }}"}
    data: {value: "{{ count_66 if count_66 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_100 }}"}
    data: {value: "{{ count_100 if count_100 > 0 else 0 }}"}
    
  # Activation / désactivation du switch
  - choose:
      - conditions: >
          {{ count_25 >= seuil_activation
             or count_33 >= seuil_activation
             or count_66 >= seuil_activation
             or count_100 >= seuil_activation }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ switch_cible }}"
    default:
      - service: input_boolean.turn_off
        target:
          entity_id: "{{ switch_cible }}"
