blueprint:
  name: Surveiller des pourcentages et activer un switch (seuils individuels)
  description: >
    Surveille une liste d’input_number (en %) et incrémente des compteurs selon les seuils (25, 33, 66, 100).
    Active ou désactive un input_boolean cible en fonction des compteurs et des seuils d'activation individuels.
  domain: automation
  input:
    surveilles:
      name: Entités surveillées
      description: Liste d’input_number représentant des pourcentages
      selector:
        entity:
          multiple: true
          domain: input_number
    switch_cible:
      name: Switch cible
      description: Input_boolean à activer/désactiver
      selector:
        entity:
          domain: input_boolean
    compteur_25:
      name: Compteur 25%
      selector:
        entity:
          domain: input_number
    seuil_activation_25:
      name: Seuil d’activation 25%
      description: Nombre minimum d’entités >25% pour activer le switch
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1
    compteur_33:
      name: Compteur 33%
      selector:
        entity:
          domain: input_number
    seuil_activation_33:
      name: Seuil d’activation 33%
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1
    compteur_66:
      name: Compteur 66%
      selector:
        entity:
          domain: input_number
    seuil_activation_66:
      name: Seuil d’activation 66%
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1
    compteur_100:
      name: Compteur 100%
      selector:
        entity:
          domain: input_number
    seuil_activation_100:
      name: Seuil d’activation 100%
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1

mode: restart

trigger:
  - platform: time_pattern
    minutes: "/1"

variables:
  surveilles: !input surveilles
  switch_cible: !input switch_cible

  compteur_25: !input compteur_25
  seuil_25: !input seuil_activation_25
  compteur_33: !input compteur_33
  seuil_33: !input seuil_activation_33
  compteur_66: !input compteur_66
  seuil_66: !input seuil_activation_66
  compteur_100: !input compteur_100
  seuil_100: !input seuil_activation_100

action:
  - variables:
      count_25: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>',25) | list | count }}
      count_33: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>',33) | list | count }}
      count_66: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>',66) | list | count }}
      count_100: >
        {{ expand(surveilles)
           | selectattr('state','defined')
           | selectattr('state','!=','unknown')
           | selectattr('state','!=','unavailable')
           | map(attribute='state') | map('float')
           | select('>=',100) | list | count }}

  # Mise à jour des compteurs
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_25 }}"}
    data: {value: "{{ count_25 if count_25 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_33 }}"}
    data: {value: "{{ count_33 if count_33 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_66 }}"}
    data: {value: "{{ count_66 if count_66 > 0 else 0 }}"}
  - service: input_number.set_value
    target: {entity_id: "{{ compteur_100 }}"}
    data: {value: "{{ count_100 if count_100 > 0 else 0 }}"}
    
  # Activation / désactivation du switch avec seuils individuels
  - choose:
      - conditions: >
          {{ count_25 >= seuil_25
             or count_33 >= seuil_33
             or count_66 >= seuil_66
             or count_100 >= seuil_100 }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ switch_cible }}"
    default:
      - service: input_boolean.turn_off
        target:
          entity_id: "{{ switch_cible }}"
